TRANSLATIONS = {
    "en": {
        "app_name": "JanMitra",
        "tagline": "Mera Chunav, Meri Awaaz",
        "nav_home": "Home",
        "nav_learn": "Learn Process",
        "nav_types": "Election Types",
        "nav_quiz": "Civic Quiz",
        "nav_chatbot": "Civic Assistant",
        "nav_live": "Live Updates",
        "nav_myarea": "My Area",
        "nav_myths": "Myth Buster",
        "nav_glossary": "Glossary",
        "nav_bookmarks": "Bookmarks",
        "nav_links": "Official Links",
        "nav_reg": "Voter Registration",
        "nav_profile": "Profile",
        "nav_settings": "Settings",
        "welcome_greeting": "Namaste, {name}!",
        "level_label": "Level {n}",
        "xp_label": "{xp} XP",
        "streak_label": "{n} Day Streak",
        "badges_label": "Badges Earned",
        "today_fact": "Election Fact of the Day",
        "continue_learning": "Continue Learning",
        "latest_update": "Latest Election Update",
        "quick_actions": "Quick Actions",
        "learn_title": "Election Journey",
        "learn_subtitle": "Level up your civic knowledge step by step",
        "stage_explore": "Explore Stage",
        "stage_done": "Completed",
        "test_me": "Quick Quiz",
        "correct_answer": "Correct! +{xp} XP",
        "wrong_answer": "Oops! Try again.",
        "quiz_title": "Civic Mastery Quiz",
        "quiz_score": "Your Score: {s}/{t}",
        "quiz_xp_earned": "XP Earned: {xp}",
        "quiz_result": "Quiz Result",
        "quiz_retry": "Try Again",
        "quiz_perfect": "Perfect Score! 🎉",
        "chatbot_title": "JanMitra AI Assistant",
        "chatbot_placeholder": "Ask about voting, registration, EVMs...",
        "chatbot_send": "Send",
        "chatbot_clear": "Clear Chat",
        "chatbot_disclaimer": "I provide official election information based on ECI guidelines.",
        "myth_title": "Myth vs Fact",
        "myth_reveal": "Reveal Truth",
        "myth_busted": "Busted!",
        "glossary_title": "Democracy Glossary",
        "glossary_search": "Search terms...",
        "glossary_bookmark": "Bookmark",
        "live_title": "Election Live Tracker",
        "live_refresh": "Refresh",
        "live_last_updated": "Last updated: {t}",
        "profile_title": "Citizen Profile",
        "profile_edit": "Edit Details",
        "profile_summary": "Your Civic Journey",
        "settings_title": "App Settings",
        "settings_theme": "Appearance",
        "settings_language": "Language",
        "settings_font": "Text Size",
        "settings_reset": "Reset Progress",
        "onboarding_lang": "Choose Language",
        "onboarding_who": "Tell us about yourself",
        "onboarding_area": "Select Your Area",
        "onboarding_complete": "Start My Journey",
        "level_up_title": "Level Up! 🎊",
        "badge_earned_title": "New Badge Earned! 🏅",
        "type_ls_name": "Lok Sabha (General Elections)",
        "type_ls_desc": "The lower house of India's Parliament.",
        "type_ls_detail": "Lok Sabha members are directly elected by the people of India. There are 543 constituencies across the country. The party or alliance that wins at least 272 seats forms the Union Government, and its leader becomes the Prime Minister. These elections are held every 5 years unless the house is dissolved earlier.",
        "type_vs_name": "Vidhan Sabha (State Assembly)",
        "type_vs_desc": "State-level elections to choose the Chief Minister.",
        "type_vs_detail": "Vidhan Sabha elections are held in each state to elect Members of the Legislative Assembly (MLAs). The majority party forms the State Government, and its leader becomes the Chief Minister. Like the Lok Sabha, these are generally held every 5 years.",
        "type_rs_name": "Rajya Sabha (Council of States)",
        "type_rs_desc": "The upper house of Parliament.",
        "type_rs_detail": "Members of Rajya Sabha are not directly elected by the people but by the elected members of the Legislative Assemblies (MLAs) of the States and Union Territories. It is a permanent body and is not subject to dissolution, but one-third of the members retire every second year.",
        "type_lb_name": "Local Bodies (Panchayats & Municipalities)",
        "type_lb_desc": "The third tier of governance.",
        "type_lb_detail": "Local body elections are held for village-level (Gram Panchayats) and city-level (Municipal Corporations) governance. These are essential for grassroots democracy and handle local issues like sanitation, water supply, and primary education.",
        "type_be_name": "By-Elections",
        "type_be_desc": "Special elections held to fill vacancies.",
        "type_be_detail": "By-elections are held when a seat in the Lok Sabha or Vidhan Sabha becomes vacant due to the death, resignation, or disqualification of the sitting member. Only the voters of that specific constituency participate."
    }
}

