TRANSLATIONS = {
    "en": {
        "app_name": "JanMitra",
        "tagline": "Mera Chunav, Meri Awaaz",
        "nav_home": "Home",
        "nav_learn": "Learn Process",
        "nav_types": "Election Types",
        "nav_quiz": "Civic Quiz",
        "nav_chatbot": "Civic Assistant",
        "nav_live": "Live Updates",
        "nav_myarea": "My Area",
        "nav_myths": "Myth Buster",
        "nav_glossary": "Glossary",
        "nav_bookmarks": "Bookmarks",
        "nav_profile": "Profile",
        "nav_settings": "Settings",
        "welcome_greeting": "Namaste, {name}!",
        "level_label": "Level {n}",
        "xp_label": "{xp} XP",
        "streak_label": "{n} Day Streak",
        "badges_label": "Badges Earned",
        "today_fact": "Election Fact of the Day",
        "continue_learning": "Continue Learning",
        "latest_update": "Latest Election Update",
        "quick_actions": "Quick Actions",
        "learn_title": "Election Journey",
        "learn_subtitle": "Level up your civic knowledge step by step",
        "stage_explore": "Explore Stage",
        "stage_done": "Completed",
        "test_me": "Quick Quiz",
        "correct_answer": "Correct! +{xp} XP",
        "wrong_answer": "Oops! Try again.",
        "quiz_title": "Civic Mastery Quiz",
        "quiz_score": "Your Score: {s}/{t}",
        "quiz_xp_earned": "XP Earned: {xp}",
        "quiz_result": "Quiz Result",
        "quiz_retry": "Try Again",
        "quiz_perfect": "Perfect Score! 🎉",
        "chatbot_title": "JanMitra AI Assistant",
        "chatbot_placeholder": "Ask about voting, registration, EVMs...",
        "chatbot_send": "Send",
        "chatbot_clear": "Clear Chat",
        "chatbot_disclaimer": "I provide official election information based on ECI guidelines.",
        "myth_title": "Myth vs Fact",
        "myth_reveal": "Reveal Truth",
        "myth_busted": "Busted!",
        "glossary_title": "Democracy Glossary",
        "glossary_search": "Search terms...",
        "glossary_bookmark": "Bookmark",
        "live_title": "Election Live Tracker",
        "live_refresh": "Refresh",
        "live_last_updated": "Last updated: {t}",
        "profile_title": "Citizen Profile",
        "profile_edit": "Edit Details",
        "profile_summary": "Your Civic Journey",
        "settings_title": "App Settings",
        "settings_theme": "Appearance",
        "settings_language": "Language",
        "settings_font": "Text Size",
        "settings_reset": "Reset Progress",
        "onboarding_lang": "Choose Language",
        "onboarding_who": "Tell us about yourself",
        "onboarding_area": "Select Your Area",
        "onboarding_complete": "Start My Journey",
        "level_up_title": "Level Up! 🎊",
        "badge_earned_title": "New Badge Earned! 🏅"
    },
    "hi": {
        "app_name": "जनमित्र",
        "tagline": "मेरा चुनाव, मेरी आवाज़",
        "nav_home": "होम",
        "nav_learn": "प्रक्रिया सीखें",
        "nav_types": "चुनाव के प्रकार",
        "nav_quiz": "क्विज़",
        "nav_chatbot": "सहायक",
        "nav_live": "लाइव अपडेट",
        "nav_myarea": "मेरा क्षेत्र",
        "nav_myths": "भ्रम और तथ्य",
        "nav_glossary": "शब्दकोश",
        "nav_bookmarks": "बुकमार्क",
        "nav_profile": "प्रोफ़ाइल",
        "nav_settings": "सेटिंग्स",
        "welcome_greeting": "नमस्ते, {name}!",
        "level_label": "स्तर {n}",
        "xp_label": "{xp} XP",
        "streak_label": "{n} दिनों का सिलसिला",
        "badges_label": "अर्जित बैज",
        "today_fact": "आज का चुनाव तथ्य",
        "continue_learning": "सीखना जारी रखें",
        "latest_update": "ताजा चुनाव अपडेट",
        "quick_actions": "त्वरित कार्रवाई",
        "learn_title": "चुनाव यात्रा",
        "learn_subtitle": "अपने नागरिक ज्ञान को चरण दर चरण बढ़ाएं",
        "stage_explore": "चरण देखें",
        "stage_done": "पूरा हुआ",
        "test_me": "त्वरित क्विज़",
        "correct_answer": "सही! +{xp} XP",
        "wrong_answer": "ओह! फिर से कोशिश करें।",
        "quiz_title": "नागरिक महारत क्विज़",
        "quiz_score": "आपका स्कोर: {s}/{t}",
        "quiz_xp_earned": "अर्जित XP: {xp}",
        "quiz_result": "क्विज़ परिणाम",
        "quiz_retry": "फिर से प्रयास करें",
        "quiz_perfect": "परफेक्ट स्कोर! 🎉",
        "chatbot_title": "जनमित्र सहायक",
        "chatbot_placeholder": "मतदान, पंजीकरण, EVM के बारे में पूछें...",
        "chatbot_send": "भेजें",
        "chatbot_clear": "चैट साफ़ करें",
        "chatbot_disclaimer": "मैं ECI दिशानिर्देशों के आधार पर आधिकारिक जानकारी प्रदान करता हूँ।",
        "myth_title": "भ्रम बनाम तथ्य",
        "myth_reveal": "सच जानें",
        "myth_busted": "भ्रम दूर!",
        "glossary_title": "लोकतंत्र शब्दकोश",
        "glossary_search": "शब्द खोजें...",
        "glossary_bookmark": "बुकमार्क",
        "live_title": "चुनाव लाइव ट्रैकर",
        "live_refresh": "रिफ्रेश",
        "live_last_updated": "अंतिम अपडेट: {t}",
        "profile_title": "नागरिक प्रोफ़ाइल",
        "profile_edit": "विवरण संपादित करें",
        "profile_summary": "आपकी नागरिक यात्रा",
        "settings_title": "ऐप सेटिंग्स",
        "settings_theme": "डार्क मोड",
        "settings_language": "भाषा",
        "settings_font": "फ़ॉन्ट आकार",
        "settings_reset": "प्रगति रीसेट करें",
        "onboarding_lang": "भाषा चुनें",
        "onboarding_who": "अपने बारे में बताएं",
        "onboarding_area": "अपना क्षेत्र चुनें",
        "onboarding_complete": "यात्रा शुरू करें",
        "level_up_title": "लेवल अप! 🎊",
        "badge_earned_title": "नया बैज मिला! 🏅"
    },
    "mr": {
        "app_name": "जनमित्र",
        "tagline": "माझे निवडणूक, माझा आवाज",
        "nav_home": "होम",
        "nav_learn": "निवडणूक प्रक्रिया",
        "nav_types": "निवडणुकीचे प्रकार",
        "nav_quiz": "क्विझ",
        "nav_chatbot": "सहाय्यक",
        "nav_live": "लाईव्ह अपडेट्स",
        "nav_myarea": "माझा परिसर",
        "nav_myths": "गैरसमज आणि तथ्य",
        "nav_glossary": "शब्दकोश",
        "nav_bookmarks": "बुकमार्क",
        "nav_profile": "प्रोफाईल",
        "nav_settings": "सेटिंग्ज",
        "welcome_greeting": "नमस्ते, {name}!",
        "level_label": "पातळी {n}",
        "xp_label": "{xp} XP",
        "streak_label": "{n} दिवसांचा सातत्य",
        "badges_label": "मिळालेले बॅज",
        "today_fact": "आजची निवडणूक माहिती",
        "continue_learning": "शिकणे सुरू ठेवा",
        "latest_update": "नवीनतम निवडणूक अपडेट",
        "quick_actions": "त्वरित कृती",
        "learn_title": "निवडणूक प्रवास",
        "learn_subtitle": "तुमचे नागरी ज्ञान टप्प्याटप्प्याने वाढवा",
        "stage_explore": "टप्पा पहा",
        "stage_done": "पूर्ण झाले",
        "test_me": "क्विक क्विझ",
        "correct_answer": "बरोबर! +{xp} XP",
        "wrong_answer": "चूक! पुन्हा प्रयत्न करा.",
        "quiz_title": "नागरी प्रभुत्व क्विझ",
        "quiz_score": "तुमचा स्कोर: {s}/{t}",
        "quiz_xp_earned": "मिळालेले XP: {xp}",
        "quiz_result": "क्विझ निकाल",
        "quiz_retry": "पुन्हा प्रयत्न करा",
        "quiz_perfect": "उत्कृष्ट! 🎉",
        "chatbot_title": "जनमित्र सहाय्यक",
        "chatbot_placeholder": "मतदान, नोंदणी, EVM बद्दल विचारा...",
        "chatbot_send": "पाठवा",
        "chatbot_clear": "चॅट साफ करा",
        "chatbot_disclaimer": "मी निवडणूक आयोगाच्या मार्गदर्शक तत्त्वांनुसार माहिती देतो.",
        "myth_title": "गैरसमज विरुद्ध तथ्य",
        "myth_reveal": "सत्य जाणून घ्या",
        "myth_busted": "गैरसमज दूर!",
        "glossary_title": "लोकशाही शब्दकोश",
        "glossary_search": "शब्द शोधा...",
        "glossary_bookmark": "बुकमार्क",
        "live_title": "निवडणूक लाईव्ह ट्रॅकर",
        "live_refresh": "रिफ्रेश",
        "live_last_updated": "अंतिम अपडेट: {t}",
        "profile_title": "नागरिक प्रोफाईल",
        "profile_edit": "तपशील संपादित करा",
        "profile_summary": "तुमचा नागरी प्रवास",
        "settings_title": "अॅप सेटिंग्ज",
        "settings_theme": "थीम निवडा",
        "settings_language": "भाषा",
        "settings_font": "फॉन्ट आकार",
        "settings_reset": "प्रगती रीसेट करा",
        "onboarding_lang": "भाषा निवडा",
        "onboarding_who": "तुमच्याबद्दल सांगा",
        "onboarding_area": "तुमचा परिसर निवडा",
        "onboarding_complete": "प्रवास सुरू करा",
        "level_up_title": "पातळी वाढली! 🎊",
        "badge_earned_title": "नवीन बॅज मिळाला! 🏅"
    }
}

class LanguageManager:
    _instance = None
    
    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(LanguageManager, cls).__new__(cls)
            cls._instance.current_lang = "en"
        return cls._instance
    
    def set_language(self, lang_code):
        if lang_code in TRANSLATIONS:
            self.current_lang = lang_code
            
    def get(self, key, **kwargs):
        text = TRANSLATIONS[self.current_lang].get(key, key)
        return text.format(**kwargs)

lang = LanguageManager()
